<!DOCTYPE html>
<html lang=Ch>
<head><meta name="generator" content="Hexo 3.9.0">
    <!-- so meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="HandheldFriendly" content="True">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="八月的第四周，来学习 Java 的异常处理机制。 异常就是不正常，程序不能正常执行，中途遇到了的问题就是异常。这次来写异常分哪些情况，以及怎么处理异常。  首先需要厘清的是，几乎所有介绍异常的总结贴，以及面试时对异常的提问，基本上说的都不光是异常，而是整个异常体系。  看一下简图就很明白了：父类 Throwable 有两个子类，一个是 Error （错误），另一个才是 Exception （异常）">
<meta name="keywords" content="Weekly Post,java">
<meta property="og:type" content="article">
<meta property="og:title" content="java 异常">
<meta property="og:url" content="http://hellopz.netlify.com/2019/08/22/java-exception/index.html">
<meta property="og:site_name" content="这里是pz阁下">
<meta property="og:description" content="八月的第四周，来学习 Java 的异常处理机制。 异常就是不正常，程序不能正常执行，中途遇到了的问题就是异常。这次来写异常分哪些情况，以及怎么处理异常。  首先需要厘清的是，几乎所有介绍异常的总结贴，以及面试时对异常的提问，基本上说的都不光是异常，而是整个异常体系。  看一下简图就很明白了：父类 Throwable 有两个子类，一个是 Error （错误），另一个才是 Exception （异常）">
<meta property="og:locale" content="Chinese">
<meta property="og:image" content="http://hellopz.netlify.com/assets/%E5%BC%82%E5%B8%B8%E4%BD%93%E7%B3%BB%EF%BC%88%E7%AE%80%E7%95%A5%EF%BC%89.png">
<meta property="og:image" content="http://hellopz.netlify.com/assets/%E5%BC%82%E5%B8%B8%E4%BD%93%E7%B3%BB.jpg">
<meta property="og:updated_time" content="2019-08-25T02:44:25.827Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="java 异常">
<meta name="twitter:description" content="八月的第四周，来学习 Java 的异常处理机制。 异常就是不正常，程序不能正常执行，中途遇到了的问题就是异常。这次来写异常分哪些情况，以及怎么处理异常。  首先需要厘清的是，几乎所有介绍异常的总结贴，以及面试时对异常的提问，基本上说的都不光是异常，而是整个异常体系。  看一下简图就很明白了：父类 Throwable 有两个子类，一个是 Error （错误），另一个才是 Exception （异常）">
<meta name="twitter:image" content="http://hellopz.netlify.com/assets/%E5%BC%82%E5%B8%B8%E4%BD%93%E7%B3%BB%EF%BC%88%E7%AE%80%E7%95%A5%EF%BC%89.png">
    
    
        
          
              <link rel="shortcut icon" href="/images/favicon.ico">
          
        
        
          
            <link rel="icon" type="image/png" href="/images/favicon-192x192.png" sizes="192x192">
          
        
        
          
            <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon.png">
          
        
    
    <!-- title -->
    <title>java 异常</title>
    <!-- styles -->
    <link rel="stylesheet" href="/css/style.css">
    <!-- rss -->
    
    
</head>

<body>
    
      <div id="header-post">
  <a id="menu-icon" href="#"><i class="fa fa-bars fa-lg"></i></a>
  <a id="menu-icon-tablet" href="#"><i class="fa fa-bars fa-lg"></i></a>
  <a id="top-icon-tablet" href="#" onclick="$('html, body').animate({ scrollTop: 0 }, 'fast');" style="display:none;"><i class="fa fa-chevron-up fa-lg"></i></a>
  <span id="menu">
    <span id="nav">
      <ul>
         
          <li><a href="/">Home</a></li>
         
          <li><a href="/2019/07/21/helloworld/">About</a></li>
         
          <li><a href="/tags/Weekly-Post/">Weekly Post</a></li>
         
          <li><a href="/tags/tips/">Tips</a></li>
        
      </ul>
    </span>
    <br/>
    <span id="actions">
      <ul>
        
        <li><a class="icon" href="/2019/09/01/递归/"><i class="fa fa-chevron-left" aria-hidden="true" onmouseover="$('#i-prev').toggle();" onmouseout="$('#i-prev').toggle();"></i></a></li>
        
        
        <li><a class="icon" href="/2019/08/15/javaIO/"><i class="fa fa-chevron-right" aria-hidden="true" onmouseover="$('#i-next').toggle();" onmouseout="$('#i-next').toggle();"></i></a></li>
        
        <li><a class="icon" href="#" onclick="$('html, body').animate({ scrollTop: 0 }, 'fast');"><i class="fa fa-chevron-up" aria-hidden="true" onmouseover="$('#i-top').toggle();" onmouseout="$('#i-top').toggle();"></i></a></li>
        <li><a class="icon" href="#"><i class="fa fa-share-alt" aria-hidden="true" onmouseover="$('#i-share').toggle();" onmouseout="$('#i-share').toggle();" onclick="$('#share').toggle();return false;"></i></a></li>
      </ul>
      <span id="i-prev" class="info" style="display:none;">Previous post</span>
      <span id="i-next" class="info" style="display:none;">Next post</span>
      <span id="i-top" class="info" style="display:none;">Back to top</span>
      <span id="i-share" class="info" style="display:none;">Share post</span>
    </span>
    <br/>
    <div id="share" style="display: none">
      <ul>
  <li><a class="icon" href="http://www.facebook.com/sharer.php?u=http://hellopz.netlify.com/2019/08/22/java-exception/"><i class="fa fa-facebook " aria-hidden="true"></i></a></li>
  <li><a class="icon" href="https://twitter.com/share?url=http://hellopz.netlify.com/2019/08/22/java-exception/&text=java 异常"><i class="fa fa-twitter " aria-hidden="true"></i></a></li>
  <li><a class="icon" href="https://pinterest.com/pin/create/bookmarklet/?url=http://hellopz.netlify.com/2019/08/22/java-exception/&is_video=false&description=java 异常"><i class="fa fa-pinterest " aria-hidden="true"></i></a></li>
</ul>

    </div>
    <div id="toc">
      <ol class="toc"><li class="toc-item toc-level-1"><a class="toc-link" href="#Error"><span class="toc-number">1.</span> <span class="toc-text">Error</span></a></li><li class="toc-item toc-level-1"><a class="toc-link" href="#Exception"><span class="toc-number">2.</span> <span class="toc-text">Exception</span></a></li><li class="toc-item toc-level-1"><a class="toc-link" href="#就地解决"><span class="toc-number">3.</span> <span class="toc-text">就地解决</span></a></li><li class="toc-item toc-level-1"><a class="toc-link" href="#异地正法"><span class="toc-number">4.</span> <span class="toc-text">异地正法</span></a></li><li class="toc-item toc-level-1"><a class="toc-link" href="#1-finally-语句块"><span class="toc-number">5.</span> <span class="toc-text">1.finally 语句块</span></a></li><li class="toc-item toc-level-1"><a class="toc-link" href="#2-异常链"><span class="toc-number">6.</span> <span class="toc-text">2.异常链</span></a></li><li class="toc-item toc-level-1"><a class="toc-link" href="#3-一个catch子句捕获多个异常"><span class="toc-number">7.</span> <span class="toc-text">3.一个catch子句捕获多个异常</span></a></li><li class="toc-item toc-level-1"><a class="toc-link" href="#4-异常抑制"><span class="toc-number">8.</span> <span class="toc-text">4.异常抑制</span></a></li><li class="toc-item toc-level-1"><a class="toc-link" href="#5-try-with-resources"><span class="toc-number">9.</span> <span class="toc-text">5. try - with - resources</span></a></li><li class="toc-item toc-level-1"><a class="toc-link" href="#6-IDEA-的快捷操作"><span class="toc-number">10.</span> <span class="toc-text">6.IDEA 的快捷操作</span></a></li></ol>
    </div>
  </span>
</div>

    
    <div class="content index width mx-auto px2 my4">
        
        <article class="post" itemscope itemtype="http://schema.org/BlogPosting">
  <header>
    
    <h1 class="posttitle" itemprop="name headline">
        java 异常
    </h1>



    <div class="meta">
      <span class="author" itemprop="author" itemscope itemtype="http://schema.org/Person">
        <span itemprop="name">这里是pz阁下</span>
      </span>
      
    <div class="postdate">
        <time datetime="2019-08-22T09:26:57.000Z" itemprop="datePublished">2019-08-22</time>
    </div>


      
    <div class="article-tag">
        <i class="fa fa-tag"></i>
        <a class="tag-link" href="/tags/Weekly-Post/">Weekly Post</a>, <a class="tag-link" href="/tags/java/">java</a>
    </div>


    </div>
  </header>
  

  <div class="content" itemprop="articleBody">
    <p>八月的第四周，来学习 Java 的异常处理机制。</p>
<p>异常就是不正常，程序不能正常执行，中途遇到了的问题就是异常。这次来写异常分哪些情况，以及怎么处理异常。</p>
<hr>
<p>首先需要厘清的是，几乎所有介绍异常的总结贴，以及面试时对异常的提问，基本上说的都不光是异常，而是整个异常体系。</p>
<p><img src="/assets/%E5%BC%82%E5%B8%B8%E4%BD%93%E7%B3%BB%EF%BC%88%E7%AE%80%E7%95%A5%EF%BC%89.png" alt="异常体系（简略）"></p>
<p>看一下简图就很明白了：父类 Throwable 有两个子类，一个是 Error （错误），另一个才是 Exception （异常）。也就是说，异常体系说的不光是异常，还把他爸和他哥一起介绍了，一家包圆了。</p>
<p>光从词语的表达上就能感受到，Error 和 Exception 的严重程度是不同的，Error （错误）是非常严重的事情，而 Exception （异常）是可以商量的事情。</p>
<ul>
<li>Error ：错误，指的是程序中很严重的问题，严重到 Java 虚拟机都无法处理，只能停止程序改bug。</li>
<li>Exception ：异常，指的是程序中的轻度问题，程序运行时遇到了之后，处理一下还可以继续执行下去（当然了，一定要处理，不能随便放任不管）。</li>
</ul>
<p>上面那张图只是一张表示 Error 和 Exception 之间关系的图，实际上的异常体系还是比较庞大的，我找到了一张稍微全一些的体系图（<a href="https://juejin.im/post/5c863f48e51d45192c4a701f" target="_blank" rel="noopener">图片来源</a>）。</p>
<p><img src="/assets/%E5%BC%82%E5%B8%B8%E4%BD%93%E7%B3%BB.jpg" alt="异常体系"></p>
<p>现在你要注意到，上图中的所有东西，比如 <code>Error</code> ，比如 <code>Exception</code> ，比如 <code>Exception</code> 里的 <code>NullPointerException</code> ，不论是错误也好异常也罢，以上的所有东西，统统都是类。Java 作为一门面向对象的语言，已经连错误、异常这些东西，都封装起来看作是一种类了。上图中的所有东西都是类，都有继承关系，都有方法，都是当做一个个的封装起来的对象来处理的。</p>
<h1 id="Error"><a href="#Error" class="headerlink" title="Error"></a>Error</h1><p>Error （错误）不是这周学习的重点，事实上其内容需要好几年 Java 实战的积累才能逐渐掌握，因为里面涉及到的具体情况都是偏硬件、偏底层的东西，比如 <code>OutOfMemoryError</code> （内存溢出错误类）。</p>
<p>我们目前只需要知道，Java 虚拟机并不会处理 Error 类，也就是说编译器不会检查 Error 类，我们在做程序设计的时候，也不应该去尝试捕获 Error 类。</p>
<h1 id="Exception"><a href="#Exception" class="headerlink" title="Exception"></a>Exception</h1><p>Exception （异常）是这周关注的重点。</p>
<p>Exception 有许许多多的子类，其中一类 <code>RuntimeException</code> 即<code>运行时异常</code>，这个子类和其他子类有所不同，怎么不同的一会再说。总之 Exception 可以分成两类，一类叫做<code>运行时异常</code>，另一类叫做<code>非运行时异常</code>。</p>
<p>怎么不同的呢？</p>
<ul>
<li><code>RuntimeException</code> 运行时异常，就是程序真的运行起来了，才能发现的异常。</li>
<li>非运行时异常，意思是说，程序即使不运行，编译器都知道将会有异常发生。也就是说，你不处理这个异常，你就别想让程序运行起来。</li>
</ul>
<p>这两类异常的主要区别在于，一种程序可以先运行起来（遇到了再报错），一种程序上来就无法运行（不用遇到了，直接报错）。</p>
<p>再换句话说，一种可以通过编译器的检查，一种无法通过编译器的检查。</p>
<p>如果从编译器检查的角度来看这两类异常，那么运行时异常（ RuntimeException ），因为可以逃避编译器的检查，因此可以被称为非检查性异常；而其他异常（也就是非运行时异常）逃不过编译器的检查，因此可以被称为检查性异常。</p>
<p>所以异常可以换一种分类方式：<code>检查性异常</code>、<code>非检查性异常</code>。这一种分类方式是更被普遍提到的，虽然它所指的其实就是运行时和非运行时，只是看待的角度不同。（现在建议你再去看一看上面的图，再理解一下分类）</p>
<ol>
<li><p>非检查性异常/运行时异常</p>
<p>属于这一类的异常中，较为常见的有：</p>
<ul>
<li><code>NullPointerException</code> 空指针异常</li>
<li><code>ArithmeticException</code> 算术异常（比如 5 除以 0 ）</li>
<li><code>ClassCastException</code>  类型转换异常</li>
<li><code>IndexOutOfBoundsException</code> 数组越界异常</li>
<li><code>ArrayStoreException</code> 数据存储异常（数组存储时数据类型不一致）</li>
</ul>
</li>
<li><p>检查性异常/非运行时异常</p>
<p>属于这一类异常中，较为常见的有：</p>
<ul>
<li><code>IOException</code> 输入输出异常</li>
<li><code>FileNotFoundException</code> 文件不存在异常（继承自 <code>IOException</code> ）</li>
<li><code>SQLException</code> SQL 语句异常</li>
<li><code>InterruptedException</code> 中断异常</li>
</ul>
</li>
</ol>
<hr>
<p>现在来学习，如果遇到了异常（ Exception ），怎么处理异常。</p>
<p>准确的说应该是，我怀疑某个地方要出现异常，我怎么提前处理这个地方，让它在程序运行之后真的遇到了异常时，仍然能在处理之后继续运行程序。</p>
<p>要注意的是，检查性异常是一定要进行处理的，不处理程序都无法运行（因为编译器直接报错），而非检查性异常和没有异常的地方（比如合理怀疑某段代码有问题），也是可以进行异常处理的。异常处理并不是只针对于异常的，而是在一切场景之下，只要我怀疑存在异常，都可以去做异常处理（大不了没碰上呗）。</p>
<p>Java 有两种异常处理方案，分别是<code>就地解决</code>（ try / catch / finally 语句）和<code>异地正法</code>（ throws ）。</p>
<h1 id="就地解决"><a href="#就地解决" class="headerlink" title="就地解决"></a>就地解决</h1><p>现在我遇到一段可能存在异常的代码，打算当场解决掉它。</p>
<p>下面这几行代码就是就地解决异常的处理方式。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">    <span class="comment">// 可能存在异常</span></span><br><span class="line">    ...</span><br><span class="line">&#125; <span class="keyword">catch</span> (Exception e) &#123;</span><br><span class="line">    <span class="comment">// 如果遇到了异常，那就执行这段代码</span></span><br><span class="line">    ...</span><br><span class="line">&#125; <span class="keyword">finally</span> &#123;</span><br><span class="line">    <span class="comment">// 不论有没有遇到异常，都执行这段代码</span></span><br><span class="line">    ...</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>有三个关键字：</p>
<ul>
<li><code>try</code> 大括号里放【可能存在异常的代码】，表示“这段代码可能有异常，我们来试试看”。</li>
<li><code>catch</code> 小括号里放【异常的类型】，大括号里放【处理异常的代码】，表示“我发现了XX异常，我要这么去处理它”。</li>
<li><code>finally</code> 大括号里放【不论如何都会执行的代码】，表示“我管你遇不遇得到异常，全都给我执行这段代码”。</li>
</ul>
<p>还是举一个具体的例子吧。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">    <span class="keyword">int</span> number = <span class="number">1</span>/<span class="number">0</span>;</span><br><span class="line">&#125; <span class="keyword">catch</span> (ArithmeticException e) &#123;</span><br><span class="line">    System.out.println(<span class="string">"发现了算术异常"</span>);</span><br><span class="line">&#125; <span class="keyword">finally</span> &#123;</span><br><span class="line">    System.out.println(<span class="string">"不论如何，都给我执行这段代码"</span>);</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="comment">// 最终会在控制台上打印两句话：</span></span><br><span class="line"><span class="comment">// 发现了算术异常</span></span><br><span class="line"><span class="comment">// 不论如何，都给我执行这段代码</span></span><br></pre></td></tr></table></figure>

<ol>
<li>程序进入 <code>try{}</code> 语句块中，执行了 <code>int number = 1/0;</code> 这行代码，因为 0 不能作为被除数，所以出现了异常。</li>
<li>通过 <code>catch(){}</code> 语句块捕捉到了 <code>ArithmeticException</code> （算术异常），你应该注意到了，小括号里放的就是这一异常的类型，如果放的是别的异常的话，那么会捕捉不到的。大括号里表示，捕捉到这一异常之后，要执行的操作，在这里是在控制台打印了一句话：“发现了算术异常”。</li>
<li><code>finally{}</code> 语句块是程序无论如何都会执行的部分，即使是没有异常也会执行。在这里发生了算数异常，打印了一句话：“不论如何，都给我执行这段代码”。其实如果没有发生异常的话，也会把这句话打印出来的。</li>
</ol>
<h1 id="异地正法"><a href="#异地正法" class="headerlink" title="异地正法"></a>异地正法</h1><p>有时我们并不想在异常出现的地方就去处理它，那么可以把异常<code>抛出去</code>。</p>
<p>抛出去（throw）又是一个翻译过来的词，在英文环境中这个词很生动，但是在汉语环境中就并不如此。我们经常听到<code>抛异常</code>这三个字，意思就是把异常给“抛”出去，不立即处理，而是在其他地方去处理。</p>
<p>比如现在有<code>方法 A</code>，<code>方法 A</code> 调用了<code>方法 B</code> ，<code>方法 B</code> 的内部出现了异常，现在就有两种解决方案：</p>
<ol>
<li><code>方法 B</code> 自己处理异常，也就是刚才说的“就地正法”。</li>
<li><code>方法 B</code> 不去解决，而是“抛”给<code>方法 A</code> 去解决。</li>
</ol>
<p>为什么不当场解决，而是抛出去让其他地方去解决，原因可能有很多，比如另一个地方拿到异常对象能做更多事情，比如程序员懒想拖到其他地方再说，等等。</p>
<p><code>抛异常</code>的动作很简单，只需要在方法名的后面（注意，不是在异常发生的原地，而是在异常发生所在的方法，那个方法的名字的位置处），加上 <code>throws XXXException</code> 就可以了。</p>
<p>举个栗子吧：</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">int</span> <span class="title">test</span><span class="params">()</span> <span class="keyword">throws</span> ArithmeticException </span>&#123;</span><br><span class="line">    <span class="keyword">int</span> number = <span class="number">1</span> / <span class="number">0</span>;</span><br><span class="line">    <span class="keyword">return</span> number;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>这里定义了一个只有两行代码的方法（方法名叫 <code>test</code>），第一行是让 <code>number = 1/0</code> （很明显出现了算术异常），第二行返回 <code>number</code> 。我并没有在异常出现的原地去处理，而是在方法名的后面，加上了 <code>throws ArithmeticException</code> ，表示抛出去了一个算术异常。之后哪里调用了这个方法，就必须去处理这个异常（或者继续抛出去）。</p>
<p>你注意，这里说的抛异常，是我们遇到了异常之后，把遇到的这个异常抛出去，而且是在方法名旁边去抛的，意思是说“每当你调用这个方法的时候，都要注意，这个方法里面有个异常要处理”。但是还有一种抛异常的方法，就是可以在随便一个地方，手动地抛出去一个异常。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">throw</span> <span class="keyword">new</span> ArithmeticException();</span><br></pre></td></tr></table></figure>

<p>比如这个样子，我手动地把一个新实例化出来的算术异常抛出去了。</p>
<p>在方法名旁边写的那个，是 <code>throws</code> ，而手动在随便一个地方抛出去的，是 <code>throw</code> 。</p>
<hr>
<p>剩下的部分太过零碎，我就分条写，写到哪里算哪里好了。</p>
<h1 id="1-finally-语句块"><a href="#1-finally-语句块" class="headerlink" title="1.finally 语句块"></a>1.<code>finally</code> 语句块</h1><p>在捕获异常当场解决的地方，我们使用了 try / catch / finally 语句，其中 <code>finally{}</code> 语句块是“无论如何都会执行的代码”。</p>
<p>这里的无论如何，真的就是无论如何，它保证了程序一定会执行这部分代码，不管发不发生异常都会执行，而且不管 <code>try{}</code> 语句块中写了什么，也都会执行。</p>
<p>注意：即使是 <code>try{}</code> 语句块中写了返回语句 <code>return xxx;</code> ，你感觉程序走到这里就停止了，其实并不是，这样也都会去执行 <code>finally{}</code> 语句块。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">    <span class="keyword">int</span> number = <span class="number">0</span>;</span><br><span class="line">    <span class="keyword">return</span> number;</span><br><span class="line">&#125; <span class="keyword">catch</span> (Exception e) &#123;</span><br><span class="line">    e.printStackTrace();</span><br><span class="line">&#125; <span class="keyword">finally</span> &#123;</span><br><span class="line">    System.out.println(<span class="string">"finally 语句块执行了"</span>);</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="comment">// 最终会在控制台上打印两行：</span></span><br><span class="line"><span class="comment">// finally 语句块执行了</span></span><br><span class="line"><span class="comment">// 0</span></span><br></pre></td></tr></table></figure>

<p>通过反编译可以发现，Java 在处理 <code>finally{}</code> 语句块时，是把它复制成两份，分别在 <code>try{}</code> 语句块和 <code>catch{}</code> 语句块后面去执行一次的。</p>
<p>而且如果 <code>finally{}</code> 语句块中写了返回语句 <code>return xxx;</code> ，将会执行这个返回语句，程序到此结束。</p>
<h1 id="2-异常链"><a href="#2-异常链" class="headerlink" title="2.异常链"></a>2.异常链</h1><p>维基百科对于异常链的解释真是太令人舒服了，一眼看懂：</p>
<blockquote>
<p>异常链是一种面向对象编程技术，指将捕获的异常包装进一个新的异常中并重新抛出的异常处理方式。原异常被保存为新异常的一个属性（比如cause）。这个想法是指一个方法应该抛出定义在相同的抽象层次上的异常，但不会丢弃更低层次的信息。</p>
</blockquote>
<p>还是举一个例子吧：</p>
<p><code>main</code> 方法调用 <code>test1</code> 方法，<code>test1</code> 方法调用 <code>test2</code> 方法。</p>
<p>其中 <code>test2</code> 方法中抛一个异常， <code>test1</code> 方法会接到 <code>test2</code> 方法抛出的异常，包裹起来再抛一个新的异常。</p>
<p>这样 <code>main</code> 方法中就会出现一个异常，这个异常里面还有一个异常（也就是接到一个包裹着异常的异常）。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">Test</span> </span>&#123;</span><br><span class="line">    </span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">        <span class="comment">// 调用 test1 方法</span></span><br><span class="line">        <span class="keyword">int</span> num = test1();</span><br><span class="line">    &#125;</span><br><span class="line">    </span><br><span class="line">    <span class="comment">// 调用 test2 方法，抛一个新的异常</span></span><br><span class="line">    <span class="function"><span class="keyword">private</span> <span class="keyword">static</span> <span class="keyword">int</span> <span class="title">test1</span><span class="params">()</span></span>&#123;</span><br><span class="line">        <span class="keyword">int</span> num = <span class="number">0</span>;</span><br><span class="line">        <span class="keyword">try</span> &#123;</span><br><span class="line">            num = test2();</span><br><span class="line">        &#125; <span class="keyword">catch</span> (Exception e) &#123;</span><br><span class="line">            e.printStackTrace();</span><br><span class="line">            <span class="keyword">throw</span> <span class="keyword">new</span> RuntimeException(<span class="string">"这里是test1的异常"</span>,e);</span><br><span class="line">        &#125;</span><br><span class="line">        <span class="keyword">return</span> num;</span><br><span class="line">    &#125;</span><br><span class="line">    </span><br><span class="line">    <span class="comment">// test2 方法中抛一个异常</span></span><br><span class="line">    <span class="function"><span class="keyword">private</span> <span class="keyword">static</span> <span class="keyword">int</span> <span class="title">test2</span><span class="params">()</span> <span class="keyword">throws</span> Exception </span>&#123;</span><br><span class="line">        <span class="keyword">throw</span> <span class="keyword">new</span> Exception(<span class="string">"这里是test2的异常"</span>);</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>控制台的打印信息如下：</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line">java.lang.Exception: 这里是test2的异常</span><br><span class="line">	at testCode.Test.test2(Test.java:<span class="number">21</span>)</span><br><span class="line">	at testCode.Test.test1(Test.java:<span class="number">12</span>)</span><br><span class="line">	at testCode.Test.main(Test.java:<span class="number">6</span>)</span><br><span class="line">Exception in thread <span class="string">"main"</span> java.lang.RuntimeException: 这里是test1的异常</span><br><span class="line">	at testCode.Test.test1(Test.java:<span class="number">15</span>)</span><br><span class="line">	at testCode.Test.main(Test.java:<span class="number">6</span>)</span><br><span class="line">Caused by: java.lang.Exception: 这里是test2的异常</span><br><span class="line">	at testCode.Test.test2(Test.java:<span class="number">21</span>)</span><br><span class="line">	at testCode.Test.test1(Test.java:<span class="number">12</span>)</span><br><span class="line">	... <span class="number">1</span> more</span><br></pre></td></tr></table></figure>

<p>这里就看到了异常链。</p>
<h1 id="3-一个catch子句捕获多个异常"><a href="#3-一个catch子句捕获多个异常" class="headerlink" title="3.一个catch子句捕获多个异常"></a>3.一个catch子句捕获多个异常</h1><p><code>JDK1.7</code> 改进了 catch 子句的语法，允许在其中指定多种异常，每个异常类型之间使用“|”来分隔。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">ExceptionHandler</span> </span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">handle</span><span class="params">()</span></span>&#123;</span><br><span class="line">        <span class="keyword">try</span> &#123;</span><br><span class="line">            <span class="comment">//..............</span></span><br><span class="line">        &#125; <span class="keyword">catch</span> (ExceptionA | ExceptionB ab) &#123; </span><br><span class="line">        &#125; <span class="keyword">catch</span> (ExceptionC c) &#123;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h1 id="4-异常抑制"><a href="#4-异常抑制" class="headerlink" title="4.异常抑制"></a>4.异常抑制</h1><p><code>JDK1.7</code> 中为 <code>Throwable类</code> 增加 <code>addSuppressed方法</code>和 <code>getSuppressed方法</code>。</p>
<p>当一个异常被抛出的时候，可能有其他异常因为该异常而被抑制住，从而无法正常抛出。这时可以通过 <code>addSuppressed方法</code> 把这些被抑制的方法记录下来，被抑制的异常会出现在抛出的异常的堆栈信息中，可以通过 <code>getSuppressed方法</code> 获取到被抑制的异常。</p>
<p>个人觉得没啥用，懒得写了。</p>
<h1 id="5-try-with-resources"><a href="#5-try-with-resources" class="headerlink" title="5. try - with - resources"></a>5. try - with - resources</h1><p>同样还是 <code>JDK1.7</code> 增加的新特性。</p>
<p>以前使用 <code>try / catch / finally</code> 语句块处理资源的时候，如果要关闭资源，需要在 <code>finally{}</code> 语句块中关闭，使用 <code>try - with - resources</code> 方式可以在 <code>try()</code> 的小括号里声明，Java 会自动关闭资源。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">BufferedReader br = <span class="keyword">new</span> BufferedReader(inputString);</span><br><span class="line"><span class="keyword">try</span> (BufferedReader br1 = br) &#123;</span><br><span class="line">    <span class="keyword">return</span> br1.readLine();</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><code>JDK1.9</code> 更进一步， <code>try()</code> 的小括号里不需要声明了，声明过程在外面也可以。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">BufferedReader br = <span class="keyword">new</span> BufferedReader(inputString);</span><br><span class="line"><span class="keyword">try</span> (br) &#123;</span><br><span class="line">    <span class="keyword">return</span> br.readLine();</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>try 后面小括号内的东西即为 resources ，resources 必须是实现 <code>java.lang.AutoCloseable</code> 或者 <code>java.io.Closeable</code> 接口的类（需要手动 close() 释放资源的）。</p>
<h1 id="6-IDEA-的快捷操作"><a href="#6-IDEA-的快捷操作" class="headerlink" title="6.IDEA 的快捷操作"></a>6.IDEA 的快捷操作</h1><p>要是使用的Java开发工具是 IDEA 的话，那么如果想对某一句代码进行异常处理，可以在这句代码写完之后，敲上“ <code>.try</code> “这四个字符，再敲回车，就可以自动为这行代码加上 try / catch 语句了。</p>
<p>例如这行代码：</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">int</span> number = <span class="number">1</span>/<span class="number">0</span>;.<span class="keyword">try</span></span><br></pre></td></tr></table></figure>

<p>写完之后敲击回车，自动变成如下代码：</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">    <span class="keyword">int</span> number = <span class="number">1</span>/<span class="number">0</span>;</span><br><span class="line">&#125; <span class="keyword">catch</span> (Exception e) &#123;</span><br><span class="line">    e.printStackTrace();</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<br>
  </div>
</article>



    </div>
    
    <footer id="footer">
  <div class="footer-left">
    Copyright &copy; 2020 pz
  </div>
  <div class="footer-right">
    <nav>
      pz阁下的blog
    </nav>
  </div>
</footer>

</body>
</html>
<!-- styles -->
<link rel="stylesheet" href="/lib/font-awesome/css/font-awesome.min.css">
<link rel="stylesheet" href="/lib/meslo-LG/styles.css">
<link rel="stylesheet" href="/lib/justified-gallery/justifiedGallery.min.css">

<!-- jquery -->
<script src="/lib/jquery/jquery.min.js"></script>
<script src="/lib/justified-gallery/jquery.justifiedGallery.min.js"></script>
<script src="/js/main.js"></script>


    <!-- Google Analytics -->
    <script type="text/javascript">
        (function(i,s,o,g,r,a,m) {i['GoogleAnalyticsObject']=r;i[r]=i[r]||function() {
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-37473492-6', 'auto');
        ga('send', 'pageview');
    </script>



